[package]
name = "tyme4rs_clib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]

[build-dependencies]
cbindgen = "0.27.0"
